<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V6QH7CG" failures="1" tests="4" name="Test4" time="28.095" errors="0" timestamp="2021-10-05T21:37:17 IDT">
  <testcase classname="Tests.HomeDelivery" name="CityNotValidTest" time="0.466">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Japanika.Functions.HomeDeliveryNotValid(Functions.java:36)
at Tests.HomeDelivery.CityNotValidTest(HomeDelivery.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CityNotValidTest -->
  <testcase classname="Tests.HomeDelivery" name="CityValidTest" time="12.303"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_1Test" time="4.08"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_2Test" time="3.671"/>
</testsuite> <!-- Test4 -->
