<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V6QH7CG" failures="1" tests="7" name="Test4" time="33.072" errors="0" timestamp="2021-10-18T21:34:59 IDT">
  <testcase classname="Tests.HomeDelivery" name="CityNotValidTest" time="0.494">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Japanika.Functions.HomeDeliveryNotValid(Functions.java:38)
at Tests.HomeDelivery.CityNotValidTest(HomeDelivery.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CityNotValidTest -->
  <testcase classname="Tests.HomeDelivery" name="CityValidTest" time="11.888"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_1Test" time="3.793"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_2Test" time="2.582"/>
  <testcase classname="Tests.HomeDelivery" name="ChangeMealDetailTest" time="4.657"/>
  <testcase classname="Tests.HomeDelivery" name="RemoveItemTest" time="2.266"/>
  <testcase classname="Tests.HomeDelivery" name="CleanCartTest" time="0.248"/>
</testsuite> <!-- Test4 -->
