<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V6QH7CG" failures="1" tests="4" name="test2+test3" time="26.551" errors="0" timestamp="2021-10-05T21:40:25 IDT">
  <testcase classname="Tests.HomeDelivery" name="CityNotValidTest" time="0.575">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Japanika.Functions.HomeDeliveryNotValid(Functions.java:36)
at Tests.HomeDelivery.CityNotValidTest(HomeDelivery.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CityNotValidTest -->
  <testcase classname="Tests.HomeDelivery" name="CityValidTest" time="12.814"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_1Test" time="3.962"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_2Test" time="3.598"/>
</testsuite> <!-- test2+test3 -->
