<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V6QH7CG" failures="1" tests="8" name="test2+test3" time="37.008" errors="0" timestamp="2021-10-20T22:24:21 IDT">
  <testcase classname="Tests.HomeDelivery" name="CityNotValidTest" time="0.591">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Japanika.Functions.HomeDeliveryNotValid(Functions.java:36)
at Tests.HomeDelivery.CityNotValidTest(HomeDelivery.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CityNotValidTest -->
  <testcase classname="Tests.HomeDelivery" name="CityValidTest" time="11.865"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_1Test" time="4.407"/>
  <testcase classname="Tests.HomeDelivery" name="AddMeal_2Test" time="2.628"/>
  <testcase classname="Tests.HomeDelivery" name="ChangeMealDetailTest" time="4.62"/>
  <testcase classname="Tests.HomeDelivery" name="RemoveItemTest" time="2.299"/>
  <testcase classname="Tests.HomeDelivery" name="CleanCartTest" time="0.276"/>
  <testcase classname="Tests.HomeDelivery" name="MinimumOrder" time="4.831"/>
</testsuite> <!-- test2+test3 -->
